"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys

if sys.platform == 'darwin':
    from setuptools import setup
    
    APP = ['RAW.py']
    DATA_FILES = []
    OPTIONS = {'argv_emulation': True,
               'packages' : ['numpy', 'scipy'],
               'resources' : './ressources'}

    setup(
          app=APP,
          data_files=DATA_FILES,
          options={'py2app': OPTIONS},
          setup_requires=['py2app'],
          )
    
elif sys.platform == 'win32':
    from distutils.core import setup
    import py2exe, os            

    opts = {
    'py2exe': { "compressed": 1,
                "optimize": 1,
              #  "ascii": 1,
                "bundle_files": 3,
                'packages' : ["matplotlib.backends.backend_wxagg",
                              "matplotlib.backends.backend_tkagg",
                              "scipy.io.matlab.streams",
                              "matplotlib.numerix.fft",
                              "matplotlib.numerix.linear_algebra",
                              "matplotlib.numerix.random_array",
                              "matplotlib.numerix.ma"
                              ],
                'excludes': [#'_tkinter'
                #             '_gtkagg', '_tkagg', '_agg2', '_cairo', '_cocoaagg',
                #             '_fltkagg', '_gtk', '_gtkcairo','_backend_gdk',
                #             '_gobject','_gtkagg','_tkinter','glade','pango',
                #             'QtCore','QtGui'
                             ],
                'dll_excludes': ['tk84.dll',
                                 'tcl84.dll',
                                 'msvcp90.dll',
                                  ]
              }
       }

    # Save matplotlib-data to mpl-data ( It is located in the matplotlib\mpl-data 
    # folder and the compiled programs will look for it in \mpl-data
    import matplotlib

    data_files = matplotlib.get_py2exe_datafiles()

    ## Add all files in the resources folder:
    currentDir = os.getcwd()
    resourcesDir = os.path.join(currentDir, 'ressources')

    for each_file in os.listdir(resourcesDir):
        if os.path.isfile(os.path.join(resourcesDir, each_file)):
            data_files.append(('ressources', [os.path.join('ressources', each_file)]))
            
    # for console program use 'console = [{"script" : "scriptname.py"}]
    # windows = 
    setup(name='BioXTAS RAW',
          version='0.98',
          author='Soren S. Nielsen',
          console=[{'script' : "RAW.py",
                    'icon_resources':[(1,'ressources\\raw.ico')],
               # 'other_resources':[(24, 1, manifest)],
               }],
          options = opts,
          zipfile = None,
          data_files = data_files)
    
    
    
    
