"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, Extension
import py2app

py_modules = ['RAWAnalysis', 'RAWCustomCtrl', 'RAWIcons', 'RAWImage', 'RAWOptions', 'RAWPlot'
 			'RAWSettings', 'SASbuild_Clibs', 'SASExceptions', 'SASFileIO', 'SASIft', 'SASImage',
 			'SASM', 'SASMarHeaderReader', 'testccode', 'tifffile', 'polygonMasking']

extensions = [Extension('bift_ext', ['bift_ext.so']), Extension('pack_ext', ['pack_ext.so']),
 			Extension('polygonmask_ext', ['polygonmask_ext.so']), Extension('ravg_ext', ['ravg_ext.so'])]


APP = ['RAW.py']
DATA_FILES = ['Resources','Tests']
OPTIONS = {'argv_emulation': True,
 'includes': py_modules,
 'matplotlib_backends': '*',
 'packages': ['wx','scipy','matplotlib','numpy','os','sys','glob','Queue','threading','math','time','subprocess',
 			'cPickle','PIL'],
 'resources': ['Resources','Tests', 'bift_ext.so', 'packc_ext.so','polygonmask_ext.so','ravg_ext.so', 'test_ext.so'],
 'site_packages': True}
 
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
    # ext_modules = extensions,
    # py_modules = py_modules
)
